on:
  release:
    types: [created]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, freebsd]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: freebsd
          - goarch: 386
            goos: freebsd
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          overwrite: true
